version: '3'

services:
  frontend:
    build: ./frontend
    command: npm run start
    env_file: .env.development.local
    ports:
      - ${POSTGRES_PORT:-8080}:8080 # host:container
    depends_on: 
      - pg_db
    restart: unless-stopped

  pg_db:
    image: postgres:14.1-alpine
    env_file: .env.development.local
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: unless-stopped
    volumes:
      - ./pg_db-data:/var/lib/postgresql/data

volumes:
  pg_db-data:
