version: '3'

services:
  frontend:
    build: ./frontend
    command: npm run start
    env_file: .env.production
    ports:
      - ${POSTGRES_PORT:-80}:80 # host:container
    restart: unless-stopped
